networks:
  lan13:
    name: lan13
    driver: macvlan
    driver_opts:
      parent: lan2
    ipam:
      config:
        - subnet: "192.168.13.0/24"
          gateway: "192.168.13.1"
volumes:
  moss-tts-nano-root:
    name: moss-tts-nano-root
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/moss-tts-nano/root
  moss-tts-nano-workspace:
    name: moss-tts-nano-workspace
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/moss-tts-nano/workspace
services:
  moss-tts-nano:
    container_name: "moss-tts-nano"
    hostname: "moss-tts-nano"
    # image: "192.168.13.73:5000/sleechengn/openmoss-tts-nano"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Asia/Shanghai
      #- HF_ENDPOINT=https://hf-mirror.com
    volumes:
      - "/mnt:/mnt"
      - "moss-tts-nano-root:/root"
      - "moss-tts-nano-workspace:/workspace"
    networks:
      lan13:
        ipv4_address: 192.168.13.65
